### ISSUE TITLE
throw error `false has not been defined` when starting the app

### ISSUE THREAD

**Issue by rakeshpudipeddi** [nielsgl/sequelize-paper-trail#11]
i have started the app following the readme
`throw new Error(modelName + ' has not been defined');` is returned when starting the app
here's the `error trace`:
Error: false has not been defined
    at Sequelize.model (/..../node_modules/sequelize/lib/sequelize.js:649:11)
    at associate (/home/..../node_modules/sequelize-paper-trail/lib/index.js:360:42)
    at /..../models/index.js:45:19
    at Array.forEach (native)
    at Object.<anonymous> (/..../index.js:43:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

could not figure out the root cause.. need your support

**Comment by nielsgl** [comment]
Please create a new issue if this is still a problem.
