### ISSUE TITLE
TypeError: Cannot read property 'current_user_request' of undefined

### ISSUE THREAD

**Issue by randallmeeker** [nielsgl/sequelize-paper-trail#12]
Seeing this error when attempting to use this.

The problem is probably with my setup as I'm using migrations and I'm not sure if I have my tables setup correctly. 

I used the migration file found in the repo and also added a `revision: integer` column to the table I want to use paper trail on.

full error 
```
{ TypeError: Cannot read property 'current_user_request' of undefined
    at Model.afterHook (/Users/randallmeeker/Projects/eventcontrol/node_modules/sequelize-paper-trail/lib/index.js:244:32)
    at /Users/randallmeeker/Projects/eventcontrol/node_modules/sequelize/lib/hooks.js:142:19
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/reduce.js:144:25)
    at bound (domain.js:280:14)
    at Object.runBound (domain.js:293:12)
    at Object.tryCatcher (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/randallmeeker/Projects/eventcontrol/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by randallmeeker** [comment]
after some deeper digging I found the issue.

**Comment by nielsgl** [comment]
Is it a problem with the library? If you want to submit a PR I'd be happy to look at it.

**Comment by eric-radiant** [comment]
@randallmeeker what was the issue, I am seeing the same thing.

**Comment by randallmeeker** [comment]
@eric-radiant my auditing requirements required more customization that this library would allow so I have since removed it. I can assure my issue was human in nature and not a problem with this library which worked as advertised.

**Comment by eric-radiant** [comment]
@randallmeeker did you go custom with your solution or use a different audit trail package?  Also do you remember what your human in nature issue was as I suspect I'm having the same/similar human issue.

**Comment by randallmeeker** [comment]
I wrote my own solution, and unfortunately, my error was never committed to git so I have no reference to what it actually was. I did use this library in my initial states for audit purposes before writing my own.
