### ISSUE TITLE
enableCompression breaks first insert on hasPaperTrail models

### ISSUE THREAD

**Issue by rorofino** [nielsgl/sequelize-paper-trail#27]
Hi,

I think i may have found a bug.
On the line 224 of index.js:

if (!instance._previousDataValues[a].dataValues && !instance.dataValues[a].dataValues)

this code runs even on the first insert on the table when compression is enable, resulting in the error:

TypeError: Cannot read property 'dataValues' of undefined

I think we r missing a simple  check of instance._previousDataValues.

**Comment by rorofino** [comment]
Adding the Log running with options.debug = true.

```
beforeHook called
instance:
User {
  dataValues:
   { active: true,
     revision: 0,
     id: null,
     login: 'rodrigo.orofino@gmail.com',
     password: '$2a$10$5DPC7JxU3cGr24NuS.g8BOZocwvWP.rA89wCBKYDIaPA8houSqGEu',
     email: 'rodrigo.orofino@gmail.com',
     updatedAt: 2017-12-11T23:45:57.589Z,
     createdAt: 2017-12-11T23:45:57.589Z },
  _previousDataValues: { login: undefined, password: '12345678', email: undefined },
  _changed: { login: true, password: true, email: true },
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: true,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [ [Object] ],
     name: { plural: 'Users', singular: 'User' },
     omitNull: false,
     hooks:
      { beforeCreate: [Object],
        beforeUpdate: [Object],
        afterCreate: [Object],
        afterUpdate: [Object] },
     sequelize:
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        queryInterface: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object] },
     uniqueKeys: {} },
  _options:
   { isNewRecord: true,
     _schema: null,
     _schemaDelimiter: '',
     attributes: undefined,
     include: undefined,
     raw: undefined,
     silent: undefined },
  __eagerlyLoadedAssociations: [],
  isNewRecord: true }
opt:
{ hooks: true,
  validate: true,
  fields:
   [ 'id',
     'active',
     'login',
     'password',
     'name',
     'email',
     'lastLogin',
     'roles',
     'tempToken',
     'tempTokenExpiration',
     'createdAt',
     'updatedAt',
     'revision' ],
  defaultFields:
   [ 'id',
     'active',
     'login',
     'password',
     'name',
     'email',
     'lastLogin',
     'roles',
     'tempToken',
     'tempTokenExpiration',
     'createdAt',
     'updatedAt',
     'revision' ],
  returning: true }
id
Unable to Sync: TypeError: Cannot read property 'dataValues' of undefined
    at C:\Users\rodri\Projetos\altomar\main-service\node_modules\sequelize-paper-trail\lib\index.js:224:45
    at arrayEach (C:\Users\rodri\Projetos\altomar\main-service\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Users\rodri\Projetos\altomar\main-service\node_modules\lodash\lodash.js:9359:14)
    at Function.beforeHook (C:\Users\rodri\Projetos\altomar\main-service\node_modules\sequelize-paper-trail\lib\index.js:222:9)
    at Promise.each.hook (C:\Users\rodri\Projetos\altomar\main-service\node_modules\sequelize\lib\hooks.js:130:35)
    at tryCatcher (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\rodri\Projetos\altomar\main-service\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by nielsgl** [comment]
Hi @rorofino finally fixed this, thanks https://github.com/nielsgl/sequelize-paper-trail/releases/tag/2.1.0
