### ISSUE TITLE
User Table Required? modelName + ' has not been defined'

### ISSUE THREAD

**Issue by kyle-copeland** [nielsgl/sequelize-paper-trail#34]
In [lines 394-396](https://github.com/nielsgl/sequelize-paper-trail/blob/master/lib/index.js#L394-L396) a relation is defined between the Revision table and the User table.

Is the user table a required table? 

Later on in the code ([lines 443-445](https://github.com/nielsgl/sequelize-paper-trail/blob/master/lib/index.js#L443-L445)): the same relation is set but there is a check to see if the userModel is provided.

Is this a bug? Lines 394-396 is causing the following error for the following code:
```
const PaperTrail = require('sequelize-paper-trail').init(app.get('sequelizeClient'), opts);
PaperTrail.defineModels({});
```

```
/Users/kcopeland/Projects/match-finder/node_modules/sequelize/lib/sequelize.js:356
      throw new Error(modelName + ' has not been defined');
      ^

Error: false has not been defined
    at Sequelize.model (/Users/kcopeland/Projects/match-finder/node_modules/sequelize/lib/sequelize.js:356:13)
    at Function.associate (/Users/kcopeland/Projects/match-finder/node_modules/sequelize-paper-trail/lib/index.js:395:40)
    at Object.keys.forEach.name (/Users/kcopeland/Projects/match-finder/src/sequelize.js:61:22)
    at Array.forEach (<anonymous>)
    at Function.app.setup (/Users/kcopeland/Projects/match-finder/src/sequelize.js:59:25)
    at Function.listen (/Users/kcopeland/Projects/match-finder/node_modules/@feathersjs/express/lib/index.js:63:12)
    at Function.listen (/Users/kcopeland/Projects/match-finder/node_modules/uberproto/lib/proto.js:30:17)
    at Object.<anonymous> (/Users/kcopeland/Projects/match-finder/src/index.js:5:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by bogdan-r** [comment]
I have the same problem. Any idea?
